### ISSUE TITLE
Light travel time correction in the flare list?

### ISSUE THREAD

**Issue by afbattaglia** [hayesla/stix_flarelist_science#3]
Hi @hayesla, Hi @hannahc243,

First of all, congratulations on the great flare list! We've been waiting for a list like this for so long, and it's wonderful that you're working on it. Thank you so much.

I have a quick question. I'm using the flare list to automatically find combined events with Hinode and IRIS. However, the csv file created at the end has no information regarding light travel time correction. I was wondering if it would make sense to add this information to the table. We could extract it from the header of each cpd file for each flare (without passing through the SPICE kernel).

What do you think?

**Comment by hannahc243** [comment]
Hi Andrea,

Yes I think that this is possible to do from the cpd file as you said. It can be added to the next version.

**Comment by hannahc243** [comment]
This is now included in PR #9!

**Comment by hayesla** [comment]
yeah that would be good. I think what we should do it have columns of "start_time_solo" and "end_time_solo" (in solar orbiter time), then include columns "start_time_earth" and "end_time_earth", and then also the timeshift (which Hannah has added).

I'll keep this issue open for the moment to inlcude it when I tidy it all up :)
